[package]
name = "sprs"
version = "0.1.0"
edition = "2024"

[dependencies]
lalrpop-util = { version = "0.22.2", features = ["lexer"] }
logos = "0.15.1"
[build-dependencies]
lalrpop = "0.22.2"
inkwell = { version = "0.7.0", features = ["llvm21-1"] }
